import { Inter } from 'next/font/google'
import styles from '@picocss/pico'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Doppio | Software House',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="dark">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
